--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["ViewportToolingFramework"]["ViewportToolingFramework"])

export type ToolbarHorizontalItem = Package.ToolbarHorizontalItem


return Package
